#Nombre

name: My_hello_world

#Evento
on:
  push:


jobs:
  Tarea1:
    run-ons: ubuntu latest


    steps:
    - name: Digo hola
      run: echo "hola a todos"


    - name: Quien soy
      run: whoami


    - name: Fecha de hoy
       run: date
